### ISSUE TITLE
缺少授權資訊

### ISSUE THREAD

**Issue by pm5** [g0v/graphics#1]
看起來非常不錯！

不過目前 repo 裡缺少授權的資訊，會讓想要取用素材的人不知如何下手 🐱 可能可以在 README 裡加一段類似（或是用任何你想用的開源授權）：

> 如果沒有特別宣告，放在這裡的素材都是以 [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) attributed to g0v contributors 授權方式釋出

**Comment by Tofuswang** [comment]
已更新！
